---
# compose 3.7 / docker version needed -> 18.06.0+

version: '3.7'

services:

  elasticsearch01:
    hostname: elasticsearch01
    container_name: elasticsearch01
    build:
      context: elasticsearch/
      args:
        ELK_VERSION: $ELK_VERSION
    environment:
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    volumes:
      - ./elasticsearch/elasticsearch.yml:/usr/share/elasticsearch/elasticsearch.yml:ro
    ports:
      - "9200:9200"
      - "9300:9300"
    networks:
        elk:
          aliases: 
            - elasticsearch_net

  elasticsearch02:
    hostname: elasticsearch02
    container_name: elasticsearch02
    build:
      context: elasticsearch/
      args:
        ELK_VERSION: $ELK_VERSION
    environment:
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    volumes:
      - ./elasticsearch/elasticsearch2.yml:/usr/share/elasticsearch/elasticsearch2.yml:ro
    networks:
        elk:
          aliases: 
            - elasticsearch_net2

  kibana01:
    hostname: kibana01
    container_name: kibana01
    build:
      context: kibana/
      args:
        ELK_VERSION: $ELK_VERSION
    volumes:
      - ./kibana/kibana.yml:/usr/share/kibana/config/kibana.yml:ro
    ports:
      - "5601:5601"
    networks:
        elk:
          aliases: 
            - kibana_net
    depends_on:
      - elasticsearch01
      - elasticsearch02

  mysql01:
    hostname: mysql01
    container_name: mysql01
    build:
      context: mysqlserver/
      args:
        MYSQL_VERSION: $MYSQL_VERSION
    volumes:
      - data:/var/lib/mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    ports:
      - "3306:3306"

networks:
  elk:
    driver: bridge

volumes:
  data:
    external: false